version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Vienna
      - NODE_RED_CREDENTIAL_SECRET=ccbbfca7789f30ee14630b26faf46d8dTAc
    ports:
      - "1880:1880"
    networks:
      - happyswing-net
    volumes:
      - ./data/node-red:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  emqx:
    image: emqx:5.0.24
    container_name: emqx
    environment:
      - EMQX_NODE_NAME=emqx@emqx.happyswing.local
      - EMQX_NODE__COOKIE=3d62b58f44ba91fbbdd0fc2bbf59619ba61bd410058c035d6f29b68f64cf21ef
    networks:
      - happyswing-net
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      #- GF_AUTH_DISABLE_LOGIN_FORM=true
      #- GF_AUTH_DISABLE_SIGNOUT_MENU=true
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    networks:
      - happyswing-net
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana/dashboards:/etc/dashboards
      #- ./data/grafana:/var/lib/grafana

  bind:
    image: ubuntu/bind9
    container_name: bind
    environment:
      - TZ=Europe/Vienna
    networks:
      - happyswing-net
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./data/bind/named.conf:/etc/bind/named.conf
      - ./data/bind/zones:/etc/bind/zones

networks:
  happyswing-net:
    name: happyswing-net
